### ISSUE TITLE
[Feature 🔮]: Podcasts + Episode support for Spotify 

### ISSUE THREAD

**Issue by Daniel1785** [InsideAgent/InsideAgentBot#10]
### Feature Request requirements.

- [X] I have searched the [issues](https://github.com/InsideAgent/InsideAgentBot/issues) page for duplicates.
- [X] I have checked the [Pull Request](https://github.com/InsideAgent/InsideAgentBot/pulls) page for this feature.
- [ ] I am willing to PR this feature myself.
- [X] I have external information to clarify the request (photo/video/files/links).

### Description

Podcast Support

### Please attach any other files/screenshots/videos/information below!

Hello! I have a podcast, but when i try to play it on the bot, it says "unknown file format". Is there a way podcasts can be supported?

**Comment by Jacrispys** [comment]
Currently not possible with spotify API, will reopen issue if they update the API.

**Comment by Jacrispys** [comment]
Will look into this for v0.10.0

**Comment by Jacrispys** [comment]
After extensive research (and PR'ing my own implementation for podcasts) it turns out that while yes you can get episode/podcast data from spotify, since podcasts don't act like songs (don't have an ISRC, not standard naming, etc) they are almost impossible to reliably find a mirror for. This means that while I can search and find a podcast on spotify, when the source player goes to find a playable version (.mp3 .wav etc) on a mirror (like youtube) it returns no results.

Unless podcasts get a standardized identifier that I can search by, or there is another easy way to grab them from a link, this will not become a feature.
